spring.application.name=backend

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_management_db
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

#photo
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}